"Notarged2LauncherUpdater"
{
	"Version" "0.9"
	"InformationOfUpdate"	"No information given."
	"DownloadUrl"	"https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.2-setup.exe"
	"Size"	"156710592"

	"UpdateUrl"	"https://sjc3.dl.dbolical.com/dl/2018/04/12/LoxNotarged2Launcher.7z?st=See9WnN18WHe_iSv2bJh9A==&e=1532725673"
	"UpdateSize"	"5076446"

	"DeleteFiles"
	{
		"Priority" "Before" //Or later.
	}

	"DeleteFolders"
	{
		"Priority" 	"Before" //Or later.
	}
}
